spring:
  application:
    name: 'Advanced-semi-formal-static-analyzer'
constants:
  location_value_coefficient: 1
  commit_importance_coefficient: 1
project:
  pythonVenv: "/home/aziz/python_env/myvenv"

  root: ""